github: ROZ-MOFUMOFU-ME
patreon: emerauda
BTC: 3FpbJ5cotwPZQn9fcdZrPv4h72XquzEvez
LTC: Lh96WZ7Rw9Wf4GDX2KXpzieneZFV5Xe5ou
MONA: MLEqE3vi11j4ZguMjkvMn5rUtze6kXbAzQ
XEM: NDBCJFIIQ7MWZERWL7A4UYHDA7UKSB67TD5B4BQ4 MESSAGE: 80929962
XLM: GBTF6TYTJVEPLIJELT7CH6L3XTK64GUX4IBFEZKI7KPQ53JB6T4TMUTR MEMO: 76525727
