node-base: &node-base
  steps:
    - checkout
    - run: npm install
    - run: npm test
jobs:
  test-v8:
    docker:
      - image: circleci/node:8
    <<: *node-base
  test-v9:
    docker:
      - image: circleci/node:9
    <<: *node-base
  test-v10:
    docker:
      - image: circleci/node:10
    <<: *node-base
  test-v11:
    docker:
      - image: circleci/node:11
    <<: *node-base
  test-v12:
    docker:
      - image: circleci/node:12
    <<: *node-base
workflows:
  version: 2
  build:
    jobs:
      - test-v8
      - test-v9
      - test-v10
      - test-v11
      - test-v12