# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  sample:
    jobs:
      - node/test:
          version: '14'
      - node/test:
          version: '15'
      - node/test:
          version: '16'
